source 'https://rubygems.org'
ruby '2.1.0'

# Used by rvm in case there's no .ruby-gemset & ruby-version
#ruby=ruby-2.1.0
#ruby-gemset=DailySoccerServer

gem 'puma', "2.8.1"

gem 'sinatra', '1.4.4'
gem 'json', '1.8.1'

group :development do
end

group :test do
  gem "rack-test", "0.6.2"
end

# Heroku production. pg is the PostgreSQL
group :production do
  gem 'pg', '0.17.1'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
